Rotate Matrix: Given an image represented by an NxN matrix, where each pixel in the image is 4
bytes, write a method to rotate the image by 90 degrees. (an you do this in place?

In [57]:
import numpy as np
inputMat = np.array([[0, 1, 2],
                     [5, 6, 7],
                     [10,11,12]])

In [55]:
n=inputMat.shape[0]
for i in range(int(n/2)):
    for j in range(int(n/2)):
        tmp = inputMat[i][j]
        inputMat[i][j]=inputMat[n-1-j][i]
        inputMat[n-1-j][i]=inputMat[n-1-i][n-1-j]
        inputMat[n-1-i][n-1-j]=inputMat[j][n-1-i]
        inputMat[j][n-1-i]=tmp
# Odd number of length
if(n%2==1):
    mid = int(n/2)
    for i in range(int(n/2)):
        tmp = inputMat[i][mid]
        inputMat[i][mid]=inputMat[mid][i]
        inputMat[mid][i]=inputMat[n-1-i][mid]
        inputMat[n-1-i][mid]=inputMat[mid][n-1-i]
        inputMat[mid][n-1-i]=tmp
    


In [56]:
print(inputMat)

[[10  5  0]
 [11  6  1]
 [12  7  2]]
