#Zero Matrix: Write an algorithm such that if an element in an MxN matrix is 0, its entire row and column are set to O.

In [74]:
import numpy as np
inputMat = np.array([[1, 1, 2, 4, 6],
                     [5, 6, 7, 0, 2],
                     [1, 0, 1, 4, 6],
                     [1, 1, 5, 2, 9]])

#Naive
m=int(inputMat.shape[0])
n=int(inputMat.shape[1])

In [75]:
def nullifyRow(r):
    for i in range(n):
        inputMat[r][i]=0
def nullifyCol(c):
    for i in range(m):
        inputMat[i][c]=0

In [49]:
# add 1 to each number
# if a number is 1 make the row and column zero
# subtract 1 from each number which is not zero

In [50]:
for i in range(m):
    for j in range(n):
        inputMat[i][j]+=1
for i in range(m):
    for j in range(n):
        if(inputMat[i][j]==1):
            print("i:",i," j:",j)
            inputMat[i][j]=0
            nullifyRow(i)
            nullifyCol(j)
for i in range(m):
    for j in range(n):
        if(inputMat[i][j]!=0):
            inputMat[i][j]-=1
print(inputMat)

i: 1  j: 3
i: 2  j: 1
[[1 0 2 0 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 5 0 9]]


In [51]:
# Method from the book

In [76]:
zeroInRow=False
zeroInCol=False
for i in range(m):
    if(inputMat[i][0]==0):
        zeroInCol=True
for j in range(n):
    if(inputMat[0][j]==0):
        zeroInRow=True
for i in range(1,m):
    for j in range(1,n):
        if(inputMat[i][j]==0):
            inputMat[i][0]=0
            inputMat[0][j]=0
for i in range(m):
    if(inputMat[i][0]==0):
        nullifyRow(i)
for j in range(n):
    if(inputMat[0][j]==0):
        nullifyCol(j)

if(zeroInRow):
    nullifyRow(0)
if(zeroInCol):
    nullifyCol(0)
print(inputMat)

[[1 0 2 0 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 5 0 9]]
